spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always

logging.level.org.springframework:
  orm:
    jpa: INFO
    jpa.JpaTransactionManager: DEBUG
  transaction: INFO
  transaction.interceptor: TRACE

spring.datasource:
  driverClassName: org.h2.Driver
  url: jdbc:h2:file:./db/ewm-main-db-test
  username: dbuser
  password: 12345