server.port: 8080

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: ${SPRING_DATASOURCE_URL}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true

  sql.init.mode: always
  application:
    name: "ewm-main-service"

ewm:
  stats:
    server:
      url: ${SERVICES_STATSSERVER_URI}