server.port: 9090

spring:
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: true
  sql.init.mode: always

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://stats-db:5432/statsdb
  username: dbuser
  password: 12345

